server:
  port: 8081
  servlet:
    context-path: /api
spring:
  application:
    name: blog-system
#  mvc:
#    static-path-pattern: /image/**
#  resources:
#    static-locations:
#      - file:D://temp-rainy//
mongodb:
  host: localhost # mongodb的连接地址
  port: 27017 # mongodb的连接端口号
  database: blog # mongodb的连接的数据库

jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: onlytoken #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24)
  tokenHead: Bearer  #JWT负载中拿到开头
